# Generated by Django 6.0.6 on 2026-06-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortner',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
