# Generated by Django 6.0.6 on 2026-06-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0002_alter_urlshortner_clicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortner',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='urlshortner',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
