# Generated by Django 6.0.6 on 2026-06-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0003_urlshortner_expires_at_urlshortner_is_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortner',
            name='short_url',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
