# Generated by Django 6.0.6 on 2026-07-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0004_alter_urlshortner_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortner',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
